services:
  app:
    container_name: ${PROJECT_NAME}_app_${PROJECT_ENV}
    hostname: ${APP_SERVER_HOST}
    restart: unless-stopped
    build: 
      context: ./
      target: runner-${PROJECT_ENV}
    environment:
      - APP_SERVER_PROTOCOL=${APP_SERVER_PROTOCOL}
      - APP_SERVER_NAME=${APP_SERVER_NAME}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
    volumes:
      - app-modules:/app/node_modules
    networks:
      - main
      
networks:
  main:
    driver: bridge
      
volumes:
  app-modules:
    driver: local